// PLEASE DO NOT EDIT THIS FILE

const DOCTORS = [
    {
        _id: "doctor1",
        name: "doctor1",
    },
    {
        _id: "doctor2",
        name: "doctor2",
    },
    {
        _id: "doctor3",
        name: "doctor3",
    },
]

const MEMBERS = [
    {
        _id: "member1",
        name: "member1",
        comments: []
    },
    {
        _id: "member2",
        name: "member2",
    },
    {
        _id: "member3",
        name: "member3",
    },
]

const COMMENTS = [
    {
        _id: "member1",
        text: "member1",
        // timestamp: ,
        placedBy: "doctor1",
    },
    {
        _id: "member2",
        name: "member2",
    },
    {
        _id: "member3",
        name: "member3",
    },
]

export { DOCTORS, MEMBERS }