// PLEASE DO NOT EDIT THIS FILE
import { DateTime } from "luxon";

const DOCTORS = [
    {
        _id: "dr1",
        name: "doctor1",
    },
    {
        _id: "dr2",
        name: "doctor2",
    },
    {
        _id: "dr3",
        name: "doctor3",
    },
    {
        _id: "dr4",
        name: "doctor4",
        profilePic: "only this doctor has profile pic, haha"
    },
]

const MEMBERS = [
    {
        _id: "member1",
        name: "member1",
        comments: ["comment1", "comment2", "comment3", ]
    },
    {
        _id: "member2",
        name: "member2",
        comments: ["comment4"]
    },
    {
        _id: "member3",
        name: "member3",
        comments: []
    },
]

const COMMENTS = [
    {
        _id: "comment1",
        text: "member1 is sick",
        timestamp: DateTime.utc(2020, 1, 1).toJSDate(),
        placedBy: "dr1",
    },
    {
        _id: "comment2",
        text: "member1 is healthy",
        timestamp: DateTime.utc(2020, 2, 2).toJSDate(),
        placedBy: "dr2",
    },
    {
        _id: "comment3",
        text: "no, member1 is sick, stop arguing about that",
        timestamp: DateTime.utc(2020, 2, 5).toJSDate(),
        placedBy: "dr1",
    },
    {
        _id: "comment4",
        text: "just for recording, first time i see this patient",
        timestamp: DateTime.utc(2020, 3, 3).toJSDate(),
        placedBy: "dr3",
    },
]

export { DOCTORS, MEMBERS, COMMENTS }
